version: "3.8"

services:
  # PostgreSQL データベース
  postgres:
    image: postgres:15
    container_name: bridge_line_postgres
    environment:
      POSTGRES_DB: bridge_line_db
      POSTGRES_USER: bridge_user
      POSTGRES_PASSWORD: bridge_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge_user -d bridge_line_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (キャッシュ・セッション管理用)
  redis:
    image: redis:7-alpine
    container_name: bridge_line_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # バックエンドAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bridge_line_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://bridge_user:bridge_password@postgres:5432/bridge_line_db
      - TEST_DATABASE_URL=postgresql+asyncpg://bridge_user:bridge_password@postgres:5432/bridge_line_test_db
      - REDIS_URL=redis://redis:6379
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Bridge Line API
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:3001"]
      - DEBUG=true
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - OPENAI_PERSONAL_API_KEY=${OPENAI_PERSONAL_API_KEY:-}
      - WEBSOCKET_URL=ws://localhost:8000/ws
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - /app/.pytest_cache
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8000/health", "--max-time", "5"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: bridge_line_network
