version: "3.8"

services:
  # PostgreSQL データベース
  postgres:
    image: postgres:15
    container_name: bridge_line_postgres_prod
    environment:
      POSTGRES_DB: bridge_line_db
      POSTGRES_USER: bridge_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bridge_user -d bridge_line_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis (キャッシュ・セッション管理用)
  redis:
    image: redis:7-alpine
    container_name: bridge_line_redis_prod
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data_prod:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # バックエンドAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: bridge_line_backend_prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://bridge_user:${POSTGRES_PASSWORD}@postgres:5432/bridge_line_db
      - REDIS_URL=redis://redis:6379
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Bridge Line API
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - DEBUG=false
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      # OpenAI API Key設定
      - OPENAI_PERSONAL_API_KEY=${OPENAI_PERSONAL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_PERSONAL_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:8000/health", "--max-time", "5"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  default:
    name: bridge_line_network_prod
