[tool.black]
# 行の長さ
line-length = 88

# タブ幅
tab-width = 4

# タブの使用
use-tabs = false

# 文字列の正規化
string-normalization = true

# 末尾のカンマ
include-trailing-comma = true

# セルフホスト
self-hosted = false

# 対象ファイル
target-version = ['py39', 'py310', 'py311', 'py312']

# 除外パターン
exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | alembic/versions
)/
'''

[tool.isort]
# プロファイル
profile = "black"

# 行の長さ
line_length = 88

# 複数行のインポート
multi_line_output = 3

# インポートの並び替え
force_sort_within_sections = true

# 既知のサードパーティライブラリ
known_third_party = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "sqlalchemy",
    "alembic",
    "pytest",
    "httpx",
    "structlog",
    "bleach",
    "websockets",
    "firebase_admin",
    "openai",
    "stripe",
]

# 既知のローカルライブラリ
known_first_party = ["app"]

# セクションの順序
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER",
]

# 除外パターン
skip_glob = [
    "*/migrations/*",
    "*/alembic/versions/*",
    "*/__pycache__/*",
    "*/.pytest_cache/*",
]

[tool.mypy]
# Pythonバージョン
python_version = "3.9"

# 厳密モード
strict = true

# 型チェックの対象
mypy_path = "app"

# 除外パターン
exclude = [
    "migrations",
    "alembic/versions",
    "__pycache__",
    ".pytest_cache",
]

# 無視するエラー
ignore_missing_imports = true

# 型チェックの詳細レベル
warn_return_any = true
warn_unused_configs = true

# 設定ファイルの場所
config_file = "pyproject.toml"
