"""create_teams_table

Revision ID: 246384b15474
Revises: 525d369dc5b6
Create Date: 2025-08-07 22:20:38.535216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246384b15474'
down_revision = 'f99283188ca1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='teams_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey')
    )
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_id', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
