"""add_chat_rooms_tables

Revision ID: 525d369dc5b6
Revises: a1b2c3d4e5f6
Create Date: 2025-08-06 00:36:06.962641

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "525d369dc5b6"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # chat_roomsテーブル作成
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "room_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_public", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("max_participants", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "current_participants", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "room_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("participants", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("moderators", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("total_messages", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "total_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="chat_rooms_created_by_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name="chat_rooms_team_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="chat_rooms_pkey"),
        sa.UniqueConstraint("room_id", name="chat_rooms_room_id_key"),
    )
    op.create_index("ix_chat_rooms_id", "chat_rooms", ["id"], unique=False)
    op.create_index("ix_chat_rooms_room_id", "chat_rooms", ["room_id"], unique=True)

    # chat_messagesテーブル作成
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "message_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "message_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "audio_file_path",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "audio_duration",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("transcription", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_edited", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("chat_room_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sender_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chat_room_id"], ["chat_rooms.id"], name="chat_messages_chat_room_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name="chat_messages_sender_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="chat_messages_pkey"),
        sa.UniqueConstraint("message_id", name="chat_messages_message_id_key"),
    )
    op.create_index("ix_chat_messages_id", "chat_messages", ["id"], unique=False)
    op.create_index(
        "ix_chat_messages_message_id", "chat_messages", ["message_id"], unique=True
    )

    # chat_room_participantsテーブル作成
    op.create_table(
        "chat_room_participants",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("chat_room_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("is_online", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_active_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("total_messages", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_room_id"],
            ["chat_rooms.id"],
            name="chat_room_participants_chat_room_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="chat_room_participants_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="chat_room_participants_pkey"),
    )
    op.create_index(
        "ix_chat_room_participants_id", "chat_room_participants", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_room_participants_id", table_name="chat_room_participants")
    op.drop_table("chat_room_participants")
    op.drop_index("ix_chat_messages_message_id", table_name="chat_messages")
    op.drop_index("ix_chat_messages_id", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_chat_rooms_room_id", table_name="chat_rooms")
    op.drop_index("ix_chat_rooms_id", table_name="chat_rooms")
    op.drop_table("chat_rooms")
    # ### end Alembic commands ###
