"""add voice_sessions table

Revision ID: a1b2c3d4e5f6
Revises: 7107ad07c5a9
Create Date: 2025-01-27 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "7107ad07c5a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "audio_file_path",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("audio_duration", sa.FLOAT(), autoincrement=False, nullable=True),
        sa.Column(
            "audio_format", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("is_public", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_analyzed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "participant_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("participants", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("analysis_summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sentiment_score", sa.FLOAT(), autoincrement=False, nullable=True),
        sa.Column("key_topics", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ended_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="voice_sessions_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="voice_sessions_pkey"),
    )
    op.create_index("ix_voice_sessions_id", "voice_sessions", ["id"], unique=False)
    op.create_index(
        "ix_voice_sessions_session_id", "voice_sessions", ["session_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_voice_sessions_session_id", table_name="voice_sessions")
    op.drop_index("ix_voice_sessions_id", table_name="voice_sessions")
    op.drop_table("voice_sessions")
    # ### end Alembic commands ###
