"""add privacy models

Revision ID: add_privacy_models
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_privacy_models'
down_revision = 'create_teams_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # プライバシーレベルとデータカテゴリのEnumを作成（存在しない場合のみ）
    op.execute("DO $$ BEGIN CREATE TYPE privacylevel AS ENUM ('public', 'team', 'private', 'confidential'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE datacategory AS ENUM ('profile', 'analysis', 'goals', 'progress', 'communication', 'performance', 'personal'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # 暗号化データテーブル
    op.create_table('encrypted_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('data_category', sa.String(length=50), nullable=False),
        sa.Column('encrypted_content', sa.Text(), nullable=False),
        sa.Column('encryption_key_id', sa.String(length=255), nullable=False),
        sa.Column('data_type', sa.String(length=100), nullable=False),
        sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_data_id'), 'encrypted_data', ['id'], unique=False)
    
    # データアクセス権限テーブル
    op.create_table('data_access_permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('granted_to_user_id', sa.Integer(), nullable=False),
        sa.Column('data_category', sa.String(length=50), nullable=False),
        sa.Column('permission_level', sa.String(length=50), nullable=False),
        sa.Column('granted_by_user_id', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['granted_to_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_access_permissions_id'), 'data_access_permissions', ['id'], unique=False)
    
    # プライバシー設定テーブル
    op.create_table('privacy_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('profile_visibility', sa.String(length=50), nullable=True),
        sa.Column('analysis_visibility', sa.String(length=50), nullable=True),
        sa.Column('goals_visibility', sa.String(length=50), nullable=True),
        sa.Column('progress_visibility', sa.String(length=50), nullable=True),
        sa.Column('communication_visibility', sa.String(length=50), nullable=True),
        sa.Column('allow_team_access', sa.Boolean(), nullable=True),
        sa.Column('allow_manager_access', sa.Boolean(), nullable=True),
        sa.Column('allow_hr_access', sa.Boolean(), nullable=True),
        sa.Column('data_retention_days', sa.Integer(), nullable=True),
        sa.Column('auto_delete_enabled', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_privacy_settings_id'), 'privacy_settings', ['id'], unique=False)
    
    # データ保持ポリシーテーブル
    op.create_table('data_retention_policies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('data_category', sa.String(length=50), nullable=False),
        sa.Column('retention_period_days', sa.Integer(), nullable=False),
        sa.Column('auto_delete_enabled', sa.Boolean(), nullable=True),
        sa.Column('archive_before_delete', sa.Boolean(), nullable=True),
        sa.Column('notify_before_deletion', sa.Boolean(), nullable=True),
        sa.Column('deletion_schedule', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_id'), 'data_retention_policies', ['id'], unique=False)
    
    # プライバシー監査ログテーブル
    op.create_table('privacy_audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('data_category', sa.String(length=50), nullable=True),
        sa.Column('target_user_id', sa.Integer(), nullable=True),
        sa.Column('permission_level', sa.String(length=50), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_audit_logs_id'), 'privacy_audit_logs', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # テーブルを削除
    op.drop_index(op.f('ix_privacy_audit_logs_id'), table_name='privacy_audit_logs')
    op.drop_table('privacy_audit_logs')
    
    op.drop_index(op.f('ix_data_retention_policies_id'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    
    op.drop_index(op.f('ix_privacy_settings_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    
    op.drop_index(op.f('ix_data_access_permissions_id'), table_name='data_access_permissions')
    op.drop_table('data_access_permissions')
    
    op.drop_index(op.f('ix_encrypted_data_id'), table_name='encrypted_data')
    op.drop_table('encrypted_data')
    
    # Enumを削除
    op.execute("DROP TYPE datacategory")
    op.execute("DROP TYPE privacylevel")
    
    # ### end Alembic commands ###
