"""Add team dynamics analysis tables

Revision ID: add_team_dynamics_tables
Revises: a1b2c3d4e5f6
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_team_dynamics_tables'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # チーム相互作用テーブル
    op.create_table('team_interactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('speaker_id', sa.Integer(), nullable=False),
        sa.Column('listener_id', sa.Integer(), nullable=False),
        sa.Column('interaction_type', sa.String(length=50), nullable=False),
        sa.Column('interaction_strength', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('duration', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['listener_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ),
        sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_interactions_id'), 'team_interactions', ['id'], unique=False)
    
    # チーム相性テーブル
    op.create_table('team_compatibilities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('member1_id', sa.Integer(), nullable=False),
        sa.Column('member2_id', sa.Integer(), nullable=False),
        sa.Column('communication_style_score', sa.Float(), nullable=True),
        sa.Column('personality_compatibility', sa.Float(), nullable=True),
        sa.Column('work_style_score', sa.Float(), nullable=True),
        sa.Column('overall_compatibility', sa.Float(), nullable=True),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['member1_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['member2_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_compatibilities_id'), 'team_compatibilities', ['id'], unique=False)
    
    # チーム結束力テーブル
    op.create_table('team_cohesions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('cohesion_score', sa.Float(), nullable=True),
        sa.Column('common_topics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('opinion_alignment', sa.Float(), nullable=True),
        sa.Column('cultural_formation', sa.Float(), nullable=True),
        sa.Column('improvement_suggestions', sa.Text(), nullable=True),
        sa.Column('analysis_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['voice_sessions.id'], ),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_cohesions_id'), 'team_cohesions', ['id'], unique=False)
    
    # チームメンバープロファイルテーブル
    op.create_table('team_member_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('team_id', sa.Integer(), nullable=False),
        sa.Column('communication_style', sa.String(length=50), nullable=True),
        sa.Column('personality_traits', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('work_preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('interaction_patterns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_profiles_id'), 'team_member_profiles', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_member_profiles_id'), table_name='team_member_profiles')
    op.drop_table('team_member_profiles')
    op.drop_index(op.f('ix_team_cohesions_id'), table_name='team_cohesions')
    op.drop_table('team_cohesions')
    op.drop_index(op.f('ix_team_compatibilities_id'), table_name='team_compatibilities')
    op.drop_table('team_compatibilities')
    op.drop_index(op.f('ix_team_interactions_id'), table_name='team_interactions')
    op.drop_table('team_interactions')
    # ### end Alembic commands ###
